<?php

class LC_Countries
{

    private $countries;
    private $capitals;

    private $no_postalcode_countries;

    function __construct()
    {
        $this->set_countries();
        $this->set_capitals();
        $this->set_no_postalcode_countries();
    }

    private function set_en_countries()
    {
        $this->countries = array(
            'AF' => 'Afghanistan',
            'AX' => 'Aland Islands',
            'AL' => 'Albania',
            'DZ' => 'Algeria',
            'AS' => 'American Samoa',
            'AD' => 'Andorra',
            'AO' => 'Angola',
            'AI' => 'Anguilla',
            'AQ' => 'Antarctica',
            'AG' => 'Antigua And Barbuda',
            'AM' => 'Armenia',
            'AW' => 'Aruba',
            'AU' => 'Australia',
            'AT' => 'Austria',
            'AZ' => 'Azerbaijan',
            'BS' => 'Bahamas',
            'BH' => 'Bahrain',
            'BD' => 'Bangladesh',
            'BB' => 'Barbados',
            'BY' => 'Belarus',
            'BE' => 'Belgium',
            'BZ' => 'Belize',
            'BJ' => 'Benin',
            'BM' => 'Bermuda',
            'BT' => 'Bhutan',
            'BQ' => 'Bonaire',
            'BA' => 'Bosnia And Herzegovina',
            'BW' => 'Botswana',
            'BV' => 'Bouvet Island',
            'IO' => 'British Indian Ocean Territory',
            'BN' => 'Brunei',
            'BG' => 'Bulgaria',
            'BF' => 'Burkina Faso',
            'BI' => 'Burundi',
            'KH' => 'Cambodia',
            'CM' => 'Cameroon',
            'CA' => 'Canada',
            'IC' => 'Canary Islands',
            'CV' => 'Cape Verde',
            'KY' => 'Cayman Islands',
            'CF' => 'Central African Republic',
            'TD' => 'Chad',
            'CL' => 'Chile',
            'CN' => 'China',
            'CX' => 'Christmas Island',
            'CC' => 'Cocos (Keeling) Islands',
            'CO' => 'Colombia',
            'CW' => 'Curaçao',
            'KM' => 'Comoros',
            'CG' => 'Congo',
            'CK' => 'Cook Islands',
            'CR' => 'Costa Rica',
            'CI' => 'Cote D\'Ivoire',
            'HR' => 'Croatia',
            'CU' => 'Cuba',
            'CY' => 'Cyprus',
            'CZ' => 'Czech Republic',
            'CD' => 'Democratic Republic of the Congo',
            'DK' => 'Denmark',
            'DJ' => 'Djibouti',
            'DM' => 'Dominica',
            'DO' => 'Dominican Republic',
            'EC' => 'Ecuador',
            'EG' => 'Egypt',
            'SV' => 'El Salvador',
            'GQ' => 'Equatorial Guinea',
            'ER' => 'Eritrea',
            'EE' => 'Estonia',
            'ET' => 'Ethiopia',
            'FK' => 'Falklands',
            'FO' => 'Faroe',
            'FJ' => 'Fiji',
            'FI' => 'Finland',
            'FR' => 'France',
            'GF' => 'French Guiana',
            'PF' => 'Polynesia',
            'TF' => 'French Southern Territories',
            'GA' => 'Gabon',
            'GM' => 'Gambia',
            'GE' => 'Georgia',
            'DE' => 'Germany',
            'GH' => 'Ghana',
            'GI' => 'Gibraltar',
            'GR' => 'Greece',
            'GL' => 'Greenland',
            'GD' => 'Grenada',
            'GP' => 'Guadeloupe',
            'GU' => 'Guam',
            'GT' => 'Guatemala',
            'GG' => 'Guernsey',
            'GN' => 'Guinea',
            'GW' => 'Guinea-Bissau',
            'GY' => 'Guyana',
            'HT' => 'Haiti',
            'HM' => 'Heard Island & Mcdonald Islands',
            'VA' => 'Vatican',
            'HN' => 'Honduras',
            'HK' => 'Hong Kong',
            'HU' => 'Hungary',
            'IS' => 'Iceland',
            'ID' => 'Indonesia',
            'IR' => 'Iran',
            'IQ' => 'Iraq',
            'IE' => 'Ireland',
            'IM' => 'Isle Of Man',
            'IL' => 'Israel',
            'IT' => 'Italy',
            'CI' => 'Ivory Coast',
            'JM' => 'Jamaica',
            'JP' => 'Japan',
            'JE' => 'Jersey',
            'JO' => 'Jordan',
            'KZ' => 'Kazakhstan',
            'KE' => 'Kenya',
            'KI' => 'Kiribati',
            'KR' => 'South Korea',
            'KW' => 'Kuwait',
            'KG' => 'Kyrgyzstan',
            'LA' => 'Laos',
            'LV' => 'Latvia',
            'LB' => 'Lebanon',
            'LS' => 'Lesotho',
            'LR' => 'Liberia',
            'LY' => 'Libya',
            'LI' => 'Liechtenstein',
            'LT' => 'Lithuania',
            'LU' => 'Luxembourg',
            'MO' => 'Macao',
            'MK' => 'North Macedonia',
            'MG' => 'Madagascar',
            'MW' => 'Malawi',
            'MY' => 'Malaysia',
            'MV' => 'Maldives',
            'ML' => 'Mali',
            'MT' => 'Malta',
            'MH' => 'Marshall',
            'MQ' => 'Martinique',
            'MR' => 'Mauritania',
            'MU' => 'Mauritius',
            'YT' => 'Mayotte',
            'MX' => 'Mexico',
            'FM' => 'Micronesia',
            'MD' => 'Moldova',
            'MC' => 'Monaco',
            'MN' => 'Mongolia',
            'ME' => 'Montenegro',
            'MS' => 'Montserrat',
            'MA' => 'Morocco',
            'MZ' => 'Mozambique',
            'MM' => 'Myanmar',
            'NA' => 'Namibia',
            'NR' => 'Nauru',
            'NP' => 'Nepal',
            'NL' => 'Netherlands',
            'AN' => 'Netherlands Antilles',
            'NC' => 'New Caledonia',
            'NZ' => 'New Zealand',
            'NI' => 'Nicaragua',
            'NE' => 'Niger',
            'NG' => 'Nigeria',
            'NU' => 'Niue',
            'NF' => 'Norfolk Island',
            'MP' => 'Northern Mariana Islands',
            'KP' => 'North Korea',
            'NO' => 'Norway',
            'OM' => 'Oman',
            'PK' => 'Pakistan',
            'PW' => 'Palau',
            'PS' => 'Palestinian Territory, Occupied',
            'PA' => 'Panama',
            'PG' => 'Papua New Guinea',
            'PY' => 'Paraguay',
            'PE' => 'Peru',
            'PH' => 'Philippines',
            'PN' => 'Pitcairn',
            'PL' => 'Poland',
            'PT' => 'Portugal',
            'PR' => 'Puerto Rico',
            'QA' => 'Qatar',
            'RE' => 'Reunion',
            'RO' => 'Romania',
            'RW' => 'Rwanda',
            'BL' => 'Saint Barthelemy',
            'SH' => 'Saint Helena',
            'KN' => 'Saint Kitts And Nevis',
            'LC' => 'Saint Lucia',
            'MF' => 'Saint Martin',
            'PM' => 'Saint Pierre And Miquelon',
            'VC' => 'Saint Vincent and the Grenadines',
            'WS' => 'Samoa',
            'SM' => 'San Marino',
            'ST' => 'Sao Tome And Principe',
            'SA' => 'Saudi Arabia',
            'SN' => 'Senegal',
            'RS' => 'Serbia',
            'SC' => 'Seychelles',
            'SL' => 'Sierra Leone',
            'SG' => 'Singapore',
            'SK' => 'Slovakia',
            'SI' => 'Slovenia',
            'SB' => 'Solomon Islands',
            'SO' => 'Somalia',
            'ZA' => 'South Africa',
            'GS' => 'South Georgia And Sandwich Isl.',
            'SS' => 'South Sudan',
            'ES' => 'Spain',
            'LK' => 'Sri Lanka',
            'SD' => 'Sudan',
            'SR' => 'Suriname',
            'SJ' => 'Svalbard And Jan Mayen',
            'SZ' => 'Swaziland',
            'SE' => 'Sweden',
            'CH' => 'Switzerland',
            'SY' => 'Syria',
            'TW' => 'Taiwan',
            'TJ' => 'Tajikistan',
            'TZ' => 'Tanzania',
            'TL' => 'Timor Leste',
            'TG' => 'Togo',
            'TK' => 'Tokelau',
            'TO' => 'Tonga',
            'TT' => 'Trinidad and Tobago',
            'TN' => 'Tunisia',
            'TR' => 'Turkey',
            'TM' => 'Turkmenistan',
            'TC' => 'Turks And Caicos Islands',
            'TV' => 'Tuvalu',
            'UG' => 'Uganda',
            'UA' => 'Ukraine',
            'AE' => 'United Arab Emirates',
            'GB' => 'United Kingdom',
            'US' => 'United States',
            'UM' => 'United States Outlying Islands',
            'UY' => 'Uruguay',
            'UZ' => 'Uzbekistan',
            'VU' => 'Vanuatu',
            'VE' => 'Venezuela',
            'VG' => 'Virgin Islands',
            'VI' => 'Virgin Islands US',
            'WF' => 'Wallis And Futuna',
            'EH' => 'Western Sahara',
            'YE' => 'Yemen',
            'XK' => 'Kosovo',
            'ZM' => 'Zambia',
            'ZW' => 'Zimbabwe',
        );
    }

    private function set_el_countries()
    {
        $this->countries = array(
            'AF' => 'Afghanistan',
            'AX' => 'Îles Aland',
            'AL' => 'Albanie',
            'DZ' => 'Algérie',
            'AS' => 'Samoa américaines',
            'AD' => 'Andorre',
            'AO' => 'Angola',
            'AI' => 'Anguilla',
            'AQ' => 'Antarctique',
            'AG' => 'Antigua-et-Barbuda',
            'AM' => 'Arménie',
            'AW' => 'Aruba',
            'AU' => 'Australie',
            'AT' => 'Autriche',
            'AZ' => 'Azerbaïdjan',
            'BS' => 'Bahamas',
            'BH' => 'Bahreïn',
            'BD' => 'Bangladesh',
            'BB' => 'Barbade',
            'BY' => 'Biélorussie',
            'BE' => 'Belgique',
            'BZ' => 'Belize',
            'BJ' => 'Bénin',
            'BM' => 'Bermudes',
            'BT' => 'Bhoutan',
            'BQ' => 'Bonaire',
            'BA' => 'Bosnie--Herzégovine',
            'BW' => 'Botswana',
            'BV' => 'Île Bouvet',
            'IO' => 'Territoire britannique de l\'océan Indien',
            'BN' => 'Brunei',
            'BG' => 'Bulgarie',
            'BF' => 'Burkina Faso',
            'BI' => 'Burundi',
            'KH' => 'Cambodge',
            'CM' => 'Cameroun',
            'CA' => 'Canada',
            'IC' => 'Îles Canaries',
            'CV' => 'Cap-Vert',
            'KY' => 'Îles Caïmans',
            'CF' => 'République centrafricaine',
            'TD' => 'Tchad',
            'CL' => 'Chili',
            'CN' => 'Chine',
            'CX' => 'Île Christmas',
            'CC' => 'Îles Cocos (Keeling)',
            'CO' => 'Colombie',
            'CW' => 'Curaçao',
            'KM' => 'Comores',
            'CG' => 'Congo',
            'CK' => 'Îles Cook',
            'CR' => 'Costa Rica',
            'CI' => 'Côte d\'Ivoire',
            'HR' => 'Croatie',
            'CU' => 'Cuba',
            'CY' => 'Chypre',
            'CZ' => 'République tchèque',
            'CD' => 'République démocratique du Congo',
            'DK' => 'Danemark',
            'DJ' => 'Djibouti',
            'DM' => 'Dominique',
            'DO' => 'République dominicaine',
            'EC' => 'Équateur',
            'EG' => 'Égypte',
            'SV' => 'El Salvador',
            'GQ' => 'Guinée équatoriale',
            'ER' => 'Érythrée',
            'EE' => 'Estonie',
            'ET' => 'Éthiopie',
            'FK' => 'Malouines',
            'FO' => 'Féroé',
            'FJ' => 'Fidji',
            'FI' => 'Finlande',
            'FR' => 'France',
            'GF' => 'Guyane française',
            'PF' => 'Polynésie',
            'TF' => 'Territoires français du Sud',
            'GA' => 'Gabon',
            'GM' => 'Gambie',
            'GE' => 'Géorgie',
            'DE' => 'Allemagne',
            'GH' => 'Ghana',
            'GI' => 'Gibraltar',
            'GR' => 'Grèce',
            'GL' => 'Groenland',
            'GD' => 'Grenade',
            'GP' => 'Guadeloupe',
            'GU' => 'Guam',
            'GT' => 'Guatemala',
            'GG' => 'Guernesey',
            'GN' => 'Guinée',
            'GW' => 'Guinée-Bissau',
            'GY' => 'Guyane',
            'HT' => 'Haïti',
            'HM' => 'Heard Island & Mcdonald Islands',
            'VA' => 'Vatican',
            'HN' => 'Honduras',
            'HK' => 'Hong Kong',
            'HU' => 'Hongrie',
            'IS' => 'Islande',
            'ID' => 'Indonésie',
            'IR' => 'Iran',
            'IQ' => 'Irak',
            'IE' => 'Irlande',
            'IM' => 'Île de Man',
            'IL' => 'Israël',
            'IT' => 'Italie',
            'CI' => 'Côte d\'Ivoire',
            'JM' => 'Jamaïque',
            'JP' => 'Japon',
            'JE' => 'Jersey',
            'JO' => 'Jordanie',
            'KZ' => 'Kazakhstan',
            'KE' => 'Kenya',
            'KI' => 'Kiribati',
            'KR' => 'Corée du Sud',
            'KW' => 'Koweït',
            'KG' => 'Kirghizstan',
            'LA' => 'Laos',
            'LV' => 'Lettonie',
            'LB' => 'Liban',
            'LS' => 'Lesotho',
            'LR' => 'Liberia',
            'LY' => 'Libye',
            'LI' => 'Liechtenstein',
            'LT' => 'Lituanie',
            'LU' => 'Luxembourg',
            'MO' => 'Macao',
            'MK' => 'Macédoine du Nord',
            'MG' => 'Madagascar',
            'MW' => 'Malawi',
            'MY' => 'Malaisie',
            'MV' => 'Maldives',
            'ML' => 'Mali',
            'MT' => 'Malte',
            'MH' => 'Marshall',
            'MQ' => 'Martinique',
            'MR' => 'Mauritanie',
            'MU' => 'Île Maurice',
            'YT' => 'Mayotte',
            'MX' => 'Mexique',
            'FM' => 'Micronésie',
            'MD' => 'Moldavie',
            'MC' => 'Monaco',
            'MN' => 'Mongolie',
            'ME' => 'Monténégro',
            'MS' => 'Montserrat',
            'MA' => 'Maroc',
            'MZ' => 'Mozambique',
            'MM' => 'Myanmar',
            'NA' => 'Namibie',
            'NR' => 'Nauru',
            'NP' => 'Népal',
            'NL' => 'Pays-Bas',
            'AN' => 'Antilles néerlandaises',
            'NC' => 'Nouvelle-Calédonie',
            'NZ' => 'Nouvelle-Zélande',
            'NI' => 'Nicaragua',
            'NE' => 'Niger',
            'NG' => 'Nigeria',
            'NU' => 'Niue',
            'NF' => 'Île Norfolk',
            'MP' => 'Îles Mariannes du Nord',
            'KP' => 'Corée du Nord',
            'NO' => 'Norvège',
            'OM' => 'Oman',
            'PK' => 'Pakistan',
            'PW' => 'Palau',
            'PS' => 'Territoire palestinien occupé',
            'PA' => 'Panama',
            'PG' => 'Papouasie-Nouvelle-Guinée',
            'PY' => 'Paraguay',
            'PE' => 'Pérou',
            'PH' => 'Philippines',
            'PN' => 'Pitcairn',
            'PL' => 'Pologne',
            'PT' => 'Portugal',
            'PR' => 'Porto Rico',
            'QA' => 'Qatar',
            'RE' => 'Réunion',
            'RO' => 'Roumanie',
            'RW' => 'Rwanda',
            'BL' => 'Saint-Barthélemy',
            'SH' => 'Sainte-Hélène',
            'KN' => 'Saint-Kitts-et-Nevis',
            'LC' => 'Sainte-Lucie',
            'MF' => 'Saint Martin',
            'PM' => 'Saint-Pierre-et-Miquelon',
            'VC' => 'Saint-Vincent-et-les-Grenadines',
            'WS' => 'Samoa',
            'SM' => 'Saint-Marin',
            'ST' => 'Sao Tomé-et-Principe',
            'SA' => 'Arabie saoudite',
            'SN' => 'Sénégal',
            'RS' => 'Serbie',
            'SC' => 'Seychelles',
            'SL' => 'Sierra Leone',
            'SG' => 'Singapour',
            'SK' => 'Slovaquie',
            'SI' => 'Slovénie',
            'SB' => 'Îles Salomon',
            'SO' => 'Somalie',
            'ZA' => 'Afrique du Sud',
            'GS' => 'Îles de Géorgie du Sud et Sandwich du Sud',
            'SS' => 'Sud-Soudan',
            'ES' => 'Espagne',
            'LK' => 'Sri Lanka',
            'SD' => 'Soudan',
            'SR' => 'Suriname',
            'SJ' => 'Svalbard et Jan Mayen',
            'SZ' => 'Swaziland',
            'SE' => 'Suède',
            'CH' => 'Suisse',
            'SY' => 'Syrie',
            'TW' => 'Taïwan',
            'TJ' => 'Tadjikistan',
            'TZ' => 'Tanzanie',
            'TL' => 'Timor Oriental',
            'TG' => 'Togo',
            'TK' => 'Tokelau',
            'TO' => 'Tonga',
            'TT' => 'Trinité-et-Tobago',
            'TN' => 'Tunisie',
            'TR' => 'Turquie',
            'TM' => 'Turkménistan',
            'TC' => 'Îles Turks et Caicos',
            'TV' => 'Tuvalu',
            'UG' => 'Ouganda',
            'UA' => 'Ukraine',
            'AE' => 'Émirats arabes unis',
            'GB' => 'Royaume-Uni',
            'US' => 'États-Unis',
            'UM' => 'Îles périphériques des États-Unis',
            'UY' => 'Uruguay',
            'UZ' => 'Ouzbékistan',
            'VU' => 'Vanuatu',
            'VE' => 'Venezuela',
            'VG' => 'Îles Vierges',
            'VI' => 'Îles Vierges américaines',
            'WF' => 'Wallis-et-Futuna',
            'EH' => 'Sahara occidental',
            'YE' => 'Yémen',
            'XK' => 'Kosovo',
            'ZM' => 'Zambie',
            'ZW' => 'Zimbabwe',
        );
    }

    private function set_countries()
    {
        $current_language = get_locale();

        if ($current_language == 'en_US') {
            $this->set_en_countries();
        } else {
            $this->set_el_countries();
        }
    }

    private function set_capitals()
    {
        $this->capitals = array(
            array("code" => "AF", "capital" => "Kabul", "postcode" => "",  "state" => ""),
            array("code" => "AX", "capital" => "Mariehamn", "postcode" => "",  "state" => ""),
            array("code" => "AL", "capital" => "Tirana", "postcode" => "",  "state" => ""),
            array("code" => "DZ", "capital" => "Algiers", "postcode" => "16000",  "state" => ""),
            array("code" => "AS", "capital" => "Pago Pago", "postcode" => "96799",  "state" => ""),
            array("code" => "AD", "capital" => "Andorra la Vella", "postcode" => "25999",  "state" => ""),
            array("code" => "AO", "capital" => "Luanda", "postcode" => "",  "state" => ""),
            array("code" => "AI", "capital" => "The Valley", "postcode" => "",  "state" => ""),
            array("code" => "AQ", "capital" => "Antarctica", "postcode" => "",  "state" => ""),
            array("code" => "AG", "capital" => "St. John's", "postcode" => "",  "state" => ""),
            array("code" => "AR", "capital" => "Buenos Aires", "postcode" => "",  "state" => ""),
            array("code" => "AM", "capital" => "Yerevan", "postcode" => "0001",  "state" => ""),
            array("code" => "AW", "capital" => "Oranjestad", "postcode" => "",  "state" => "",  "suburb" => "POS ABAO"),
            array("code" => "AU", "capital" => "Canberra", "postcode" => "2601",  "state" => "AF"),
            array("code" => "AT", "capital" => "Vienna", "postcode" => "1125",  "state" => ""),
            array("code" => "AZ", "capital" => "Baku", "postcode" => "1001",  "state" => ""),
            array("code" => "BS", "capital" => "Nassau", "postcode" => "",  "state" => "", "suburb" => "LYFORD CAY"),
            array("code" => "BH", "capital" => "Manama", "postcode" => "",  "state" => ""),
            array("code" => "BD", "capital" => "Dhaka", "postcode" => "1100",  "state" => ""),
            array("code" => "BB", "capital" => "Bridgetown", "postcode" => "",  "state" => "", "suburb" => "BRIDGETOWN"),
            array("code" => "BY", "capital" => "Minsk", "postcode" => "220021",  "state" => ""),
            array("code" => "BE", "capital" => "Brussels", "postcode" => "1000",  "state" => ""),
            array("code" => "BZ", "capital" => "Belmopan", "postcode" => "",  "state" => "", "suburb" => "BELMOPAN"),
            array("code" => "BJ", "capital" => "Cotonou", "postcode" => "",  "state" => ""),
            array("code" => "BM", "capital" => "Hamilton", "postcode" => "",  "state" => "", "suburb" => "HAMILTON"),
            array("code" => "BT", "capital" => "Thimphu", "postcode" => "",  "state" => ""),
            array("code" => "BO", "capital" => "Sucre", "postcode" => "",  "state" => "", "suburb" => "SUCRE"),
            array("code" => "BQ", "capital" => "Kralendijk", "postcode" => "",  "state" => ""),
            array("code" => "BA", "capital" => "Sarajevo", "postcode" => "71000",  "state" => ""),
            array("code" => "BW", "capital" => "Gaborone", "postcode" => "",  "state" => ""),
            array("code" => "BR", "capital" => "Brasilia", "postcode" => "72300",  "state" => "DF"),
            array("code" => "IO", "capital" => "Diego Garcia", "postcode" => "",  "state" => ""),
            array("code" => "BN", "capital" => "Bandar Seri Begawan", "postcode" => "BS8711",  "state" => ""),
            array("code" => "BG", "capital" => "Sofia", "postcode" => "1040",  "state" => ""),
            array("code" => "BF", "capital" => "Ouagadougou", "postcode" => "",  "state" => ""),
            array("code" => "BI", "capital" => "Tonle Basak - Phnom Penh", "postcode" => "120101",  "state" => ""),
            array("code" => "CM", "capital" => "Yaounde", "postcode" => "",  "state" => ""),
            array("code" => "CA", "capital" => "Ottawa", "postcode" => "K1A0A",  "state" => "ON"),
            array("code" => "CV", "capital" => "Praia", "postcode" => "",  "state" => ""),
            array("code" => "KY", "capital" => "George Town", "postcode" => "",  "state" => "", "suburb" => "GEORGE TOWN"),
            array("code" => "CF", "capital" => "Bangui", "postcode" => "",  "state" => ""),
            array("code" => "TD", "capital" => "N'Djamena", "postcode" => "",  "state" => ""),
            array("code" => "CL", "capital" => "Santiago", "postcode" => "",  "state" => "", "suburb" => "ESTACION CENTRAL"),
            array("code" => "CN", "capital" => "Beijing", "postcode" => "100012",  "state" => "BD"),
            array("code" => "CX", "capital" => "Flying Fish Cove", "postcode" => "",  "state" => ""),
            array("code" => "CC", "capital" => "West Island", "postcode" => "",  "state" => ""),
            array("code" => "CO", "capital" => "Bogota", "postcode" => "110121",  "state" => ""),
            array("code" => "KM", "capital" => "Moroni", "postcode" => "",  "state" => ""),
            array("code" => "CG", "capital" => "Brazzaville", "postcode" => "",  "state" => ""),
            array("code" => "CD", "capital" => "Kinshasa", "postcode" => "",  "state" => "DC"),
            array("code" => "CK", "capital" => "Avarua", "postcode" => "",  "state" => ""),
            array("code" => "CR", "capital" => "San Jose", "postcode" => "",  "state" => "", "suburb" => "ASERRI SAN JOSE"),
            array("code" => "CI", "capital" => "Yamoussoukro", "postcode" => "",  "state" => ""),
            array("code" => "HR", "capital" => "Zagreb", "postcode" => "10000",  "state" => ""),
            array("code" => "CU", "capital" => "Havana", "postcode" => "",  "state" => ""),
            array("code" => "CW", "capital" => "Willemstad", "postcode" => "",  "state" => ""),
            array("code" => "CY", "capital" => "Nicosia", "postcode" => "1010",  "state" => "AC"),
            array("code" => "CZ", "capital" => "Prague", "postcode" => "11101",  "state" => "PR"),
            array("code" => "DK", "capital" => "Copenhagen K", "postcode" => "1265",  "state" => ""),
            array("code" => "DJ", "capital" => "Djibouti", "postcode" => "",  "state" => ""),
            array("code" => "DM", "capital" => "Roseau", "postcode" => "",  "state" => "", "suburb" => "CANEFIELD"),
            array("code" => "DO", "capital" => "Santo Domingo", "postcode" => "",  "state" => "", "suburb" => "NIGUA SAN CRISTOBAL"),
            array("code" => "EC", "capital" => "Quito", "postcode" => "170101",  "state" => ""),
            array("code" => "EG", "capital" => "Cairo", "postcode" => "",  "state" => ""),
            array("code" => "SV", "capital" => "San Salvador", "postcode" => "",  "state" => "", "suburb" => "SAN SALVADOR"),
            array("code" => "GQ", "capital" => "Malabo", "postcode" => "",  "state" => ""),
            array("code" => "ER", "capital" => "Asmara", "postcode" => "",  "state" => ""),
            array("code" => "EE", "capital" => "Tallinn", "postcode" => "10146",  "state" => ""),
            array("code" => "ET", "capital" => "Addis Ababa", "postcode" => "",  "state" => ""),
            array("code" => "FK", "capital" => "Stanley", "postcode" => "",  "state" => ""),
            array("code" => "FJ", "capital" => "Suva", "postcode" => "",  "state" => ""),
            array("code" => "FI", "capital" => "Helsinki", "postcode" => "00100",  "state" => ""),
            array("code" => "FR", "capital" => "Paris", "postcode" => "75020",  "state" => ""),
            array("code" => "GF", "capital" => "Cayenne", "postcode" => "97300",  "state" => ""),
            array("code" => "PF", "capital" => "Papeete", "postcode" => "98713",  "state" => ""),
            array("code" => "TF", "capital" => "Port-aux-Francais", "postcode" => "",  "state" => ""),
            array("code" => "GA", "capital" => "Libreville", "postcode" => "",  "state" => ""),
            array("code" => "GM", "capital" => "Banjul", "postcode" => "",  "state" => ""),
            array("code" => "GE", "capital" => "Tbilisi", "postcode" => "0101",  "state" => ""),
            array("code" => "DE", "capital" => "Berlin", "postcode" => "10115",  "state" => "BE"),
            array("code" => "GH", "capital" => "Accra", "postcode" => "",  "state" => ""),
            array("code" => "GI", "capital" => "Gibraltar", "postcode" => "",  "state" => ""),
            array("code" => "GR", "capital" => "Athens", "postcode" => "10160",  "state" => "BG"),
            array("code" => "GL", "capital" => "Nuuk", "postcode" => "3900",  "state" => ""),
            array("code" => "GD", "capital" => "St. George's", "postcode" => "",  "state" => "", "suburb" => "SAINT GEORGE`S"),
            array("code" => "GP", "capital" => "Basse-Terre", "postcode" => "97100",  "state" => ""),
            array("code" => "GU", "capital" => "Hagatna", "postcode" => "96932",  "state" => ""),
            array("code" => "GT", "capital" => "Guatemala", "postcode" => "",  "state" => "", "suburb" => "GUATEMALA CITY"),
            array("code" => "GG", "capital" => "St Peter Port", "postcode" => "GY1",  "state" => ""),
            array("code" => "GN", "capital" => "Conakry", "postcode" => "",  "state" => ""),
            array("code" => "GW", "capital" => "Bissau", "postcode" => "",  "state" => ""),
            array("code" => "GY", "capital" => "Georgetown", "postcode" => "",  "state" => "", "suburb" => "BETERVERWAGTING"),
            array("code" => "HT", "capital" => "Port-au-Prince", "postcode" => "",  "state" => "", "suburb" => "BOURDON"),
            array("code" => "VA", "capital" => "Vatican City", "postcode" => "",  "state" => ""),
            array("code" => "HN", "capital" => "Tegucigalpa", "postcode" => "",  "state" => "", "suburb" => "TEGUCIGALPA"),
            array("code" => "HK", "capital" => "Hong Kong", "postcode" => "",  "state" => ""),
            array("code" => "HU", "capital" => "Budapest", "postcode" => "1000",  "state" => ""),
            array("code" => "IS", "capital" => "Reykjavik", "postcode" => "126",  "state" => ""),
            array("code" => "IN", "capital" => "New Delhi", "postcode" => "110001",  "state" => "07"),
            array("code" => "ID", "capital" => "Jakarta", "postcode" => "14360",  "state" => ""),
            array("code" => "IR", "capital" => "Tehran", "postcode" => "",  "state" => ""),
            array("code" => "IQ", "capital" => "Baghdad", "postcode" => "",  "state" => ""),
            array("code" => "IE", "capital" => "Dublin", "postcode" => "",  "state" => "", "suburb" => "PERRYSTOWN"),
            array("code" => "IM", "capital" => "Douglas, Isle of Man", "postcode" => "",  "state" => ""),
            array("code" => "IL", "capital" => "Jerusalem", "postcode" => "9713000",  "state" => ""),
            array("code" => "IT", "capital" => "Rome", "postcode" => "00192",  "state" => ""),
            array("code" => "JM", "capital" => "Kingston", "postcode" => "",  "state" => "", "suburb" => "KINGSTON"),
            array("code" => "JP", "capital" => "Tokyo", "postcode" => "1628656",  "state" => ""),
            array("code" => "JE", "capital" => "Saint Helier", "postcode" => "",  "state" => ""),
            array("code" => "JO", "capital" => "Amman", "postcode" => "",  "state" => "", "suburb" => "UM ALSOUS"),
            array("code" => "KZ", "capital" => "Astana", "postcode" => "",  "state" => ""),
            array("code" => "KE", "capital" => "Nairobi", "postcode" => "",  "state" => ""),
            array("code" => "KI", "capital" => "Tarawa", "postcode" => "",  "state" => ""),
            array("code" => "KP", "capital" => "Pyongyang", "postcode" => "",  "state" => ""),
            array("code" => "KR", "capital" => "Seoul", "postcode" => "05847",  "state" => ""),
            array("code" => "XK", "capital" => "Pristina", "postcode" => "",  "state" => ""),
            array("code" => "KW", "capital" => "Kuwait City", "postcode" => "",  "state" => ""),
            array("code" => "KG", "capital" => "Bishkek", "postcode" => "",  "state" => ""),
            array("code" => "LA", "capital" => "Vientiane", "postcode" => "",  "state" => ""),
            array("code" => "LV", "capital" => "Riga", "postcode" => "1167",  "state" => ""),
            array("code" => "LB", "capital" => "Beirut", "postcode" => "",  "state" => ""),
            array("code" => "LS", "capital" => "Maseru", "postcode" => "",  "state" => ""),
            array("code" => "LR", "capital" => "Monrovia", "postcode" => "",  "state" => ""),
            array("code" => "LY", "capital" => "Tripolis", "postcode" => "",  "state" => ""),
            array("code" => "LI", "capital" => "Vaduz", "postcode" => "",  "state" => ""),
            array("code" => "LT", "capital" => "Vilnius", "postcode" => "01101",  "state" => ""),
            array("code" => "LU", "capital" => "Luxembourg", "postcode" => "1334",  "state" => ""),
            array("code" => "MO", "capital" => "Macao", "postcode" => "",  "state" => ""),
            array("code" => "MK", "capital" => "Skopje", "postcode" => "1000",  "state" => ""),
            array("code" => "MG", "capital" => "Antananarivo", "postcode" => "",  "state" => ""),
            array("code" => "MW", "capital" => "Lilongwe", "postcode" => "",  "state" => ""),
            array("code" => "MY", "capital" => "Kuala Lumpur", "postcode" => "",  "state" => ""),
            array("code" => "MV", "capital" => "Male", "postcode" => "",  "state" => ""),
            array("code" => "ML", "capital" => "Bamako", "postcode" => "",  "state" => ""),
            array("code" => "MT", "capital" => "Valletta", "postcode" => "",  "state" => ""),
            array("code" => "MH", "capital" => "Majuro", "postcode" => "96960",  "state" => ""),
            array("code" => "MQ", "capital" => "Fort-de-France", "postcode" => "97200",  "state" => ""),
            array("code" => "MR", "capital" => "Nouakchott", "postcode" => "",  "state" => ""),
            array("code" => "MU", "capital" => "Port Louis", "postcode" => "",  "state" => ""),
            array("code" => "YT", "capital" => "Mamoudzou", "postcode" => "",  "state" => ""),
            array("code" => "MX", "capital" => "MEXICALI", "postcode" => "21000",  "state" => "BC"),
            array("code" => "FM", "capital" => "Palikir", "postcode" => "",  "state" => ""),
            array("code" => "MD", "capital" => "Chisinau", "postcode" => "2001",  "state" => ""),
            array("code" => "MC", "capital" => "Monaco", "postcode" => "98000",  "state" => ""),
            array("code" => "MN", "capital" => "Ulan Bator", "postcode" => "",  "state" => ""),
            array("code" => "ME", "capital" => "Podgorica", "postcode" => "",  "state" => ""),
            array("code" => "MS", "capital" => "Plymouth", "postcode" => "",  "state" => ""),
            array("code" => "MA", "capital" => "Rabat", "postcode" => "",  "state" => ""),
            array("code" => "MZ", "capital" => "Maputo", "postcode" => "",  "state" => ""),
            array("code" => "MM", "capital" => "Nay Pyi Taw", "postcode" => "",  "state" => ""),
            array("code" => "NA", "capital" => "Windhoek", "postcode" => "",  "state" => ""),
            array("code" => "NR", "capital" => "Yaren", "postcode" => "",  "state" => ""),
            array("code" => "NP", "capital" => "Kathmandu", "postcode" => "60000",  "state" => ""),
            array("code" => "NL", "capital" => "Amsterdam", "postcode" => "1044",  "state" => ""),
            array("code" => "AN", "capital" => "Willemstad", "postcode" => "",  "state" => ""),
            array("code" => "NC", "capital" => "Noumea", "postcode" => "",  "state" => ""),
            array("code" => "NZ", "capital" => "Wellington", "postcode" => "6022",  "state" => ""),
            array("code" => "NI", "capital" => "Managua", "postcode" => "",  "state" => ""),
            array("code" => "NE", "capital" => "Niamey", "postcode" => "",  "state" => ""),
            array("code" => "NG", "capital" => "Abuja", "postcode" => "",  "state" => ""),
            array("code" => "NU", "capital" => "Alofi", "postcode" => "",  "state" => ""),
            array("code" => "NF", "capital" => "Kingston", "postcode" => "",  "state" => ""),
            array("code" => "MP", "capital" => "Saipan", "postcode" => "96950",  "state" => "AA"),
            array("code" => "NO", "capital" => "Oslo", "postcode" => "0010",  "state" => ""),
            array("code" => "OM", "capital" => "Muscat", "postcode" => "",  "state" => ""),
            array("code" => "PK", "capital" => "Islamabad", "postcode" => "44000",  "state" => ""),
            array("code" => "PW", "capital" => "Melekeok", "postcode" => "",  "state" => ""),
            array("code" => "PS", "capital" => "East Jerusalem", "postcode" => "",  "state" => ""),
            array("code" => "PA", "capital" => "Panama City", "postcode" => "",  "state" => "", "suburb" => "PANAMA CITY"),
            array("code" => "PG", "capital" => "Port Moresby", "postcode" => "121",  "state" => ""),
            array("code" => "PY", "capital" => "Asuncion", "postcode" => "",  "state" => "", "suburb" => "ASUNCION"),
            array("code" => "PE", "capital" => "Lima", "postcode" => "",  "state" => "", "suburb" => "CERCADO"),
            array("code" => "PH", "capital" => "Manila", "postcode" => "1011",  "state" => ""),
            array("code" => "PN", "capital" => "Adamstown", "postcode" => "",  "state" => ""),
            array("code" => "PL", "capital" => "Warsawa", "postcode" => "01626",  "state" => ""),
            array("code" => "PT", "capital" => "Lisbon", "postcode" => "1169062",  "state" => ""),
            array("code" => "PR", "capital" => "San Juan", "postcode" => "00795",  "state" => "AA"),
            array("code" => "QA", "capital" => "Doha", "postcode" => "",  "state" => ""),
            array("code" => "RE", "capital" => "Saint-Denis", "postcode" => "97400",  "state" => ""),
            array("code" => "RO", "capital" => "Bucharest", "postcode" => "020011",  "state" => "S2"),
            array("code" => "RU", "capital" => "Moscow", "postcode" => "102101",  "state" => ""),
            array("code" => "RW", "capital" => "Kigali", "postcode" => "",  "state" => "", "suburb" => "AIRPORT AREA"),
            array("code" => "BL", "capital" => "Gustavia", "postcode" => "",  "state" => ""),
            array("code" => "SH", "capital" => "Jamestown", "postcode" => "STHL1ZZ",  "state" => ""),
            array("code" => "KN", "capital" => "Basseterre", "postcode" => "",  "state" => "", "suburb" => "CAYON"),
            array("code" => "LC", "capital" => "Castries", "postcode" => "",  "state" => "", "suburb" => "ROSEAU BAY"),
            array("code" => "MF", "capital" => "Marigot", "postcode" => "",  "state" => ""),
            array("code" => "PM", "capital" => "Saint-Pierre", "postcode" => "",  "state" => ""),
            array("code" => "VC", "capital" => "Kingstown", "postcode" => "",  "state" => "", "suburb" => "KINGSTOWN"),
            array("code" => "WS", "capital" => "Apia", "postcode" => "",  "state" => ""),
            array("code" => "SM", "capital" => "San Marino", "postcode" => "47890",  "state" => ""),
            array("code" => "ST", "capital" => "Sao Tome", "postcode" => "",  "state" => ""),
            array("code" => "SA", "capital" => "Riyadh", "postcode" => "",  "state" => "", "suburb" => "AD DIRIYAH"),
            array("code" => "SN", "capital" => "Dakar", "postcode" => "",  "state" => ""),
            array("code" => "RS", "capital" => "Belgrade", "postcode" => "11000",  "state" => ""),
            array("code" => "CS", "capital" => "Belgrade", "postcode" => "11000",  "state" => ""),
            array("code" => "SC", "capital" => "Victoria", "postcode" => "",  "state" => ""),
            array("code" => "SL", "capital" => "Freetown", "postcode" => "",  "state" => ""),
            array("code" => "SG", "capital" => "SINGAPORE", "postcode" => "088662",  "state" => ""),
            array("code" => "SX", "capital" => "Philipsburg", "postcode" => "",  "state" => ""),
            array("code" => "SK", "capital" => "Bratislava", "postcode" => "81782",  "state" => ""),
            array("code" => "SI", "capital" => "Ljubljana", "postcode" => "1102",  "state" => ""),
            array("code" => "SB", "capital" => "Honiara", "postcode" => "",  "state" => ""),
            array("code" => "SO", "capital" => "Mogadishu", "postcode" => "",  "state" => ""),
            array("code" => "ZA", "capital" => "Pretoria", "postcode" => "0002",  "state" => ""),
            array("code" => "GS", "capital" => "Grytviken", "postcode" => "",  "state" => ""),
            array("code" => "SS", "capital" => "Juba", "postcode" => "",  "state" => ""),
            array("code" => "ES", "capital" => "Madrid", "postcode" => "28033",  "state" => ""),
            array("code" => "LK", "capital" => "Colombo", "postcode" => "",  "state" => ""),
            array("code" => "SD", "capital" => "Khartoum", "postcode" => "",  "state" => ""),
            array("code" => "SR", "capital" => "Paramaribo", "postcode" => "",  "state" => ""),
            array("code" => "SJ", "capital" => "Longyearbyen", "postcode" => "",  "state" => ""),
            array("code" => "SZ", "capital" => "Mbabane", "postcode" => "H100",  "state" => ""),
            array("code" => "SE", "capital" => "Stockholm", "postcode" => "11368",  "state" => ""),
            array("code" => "CH", "capital" => "Zurich", "postcode" => "8000",  "state" => ""),
            array("code" => "SY", "capital" => "Damascus", "postcode" => "",  "state" => ""),
            array("code" => "TW", "capital" => "Taipei city", "postcode" => "11237",  "state" => ""),
            array("code" => "TJ", "capital" => "Dushanbe", "postcode" => "734000",  "state" => ""),
            array("code" => "TZ", "capital" => "Dodoma", "postcode" => "",  "state" => ""),
            array("code" => "TH", "capital" => "Bangkok", "postcode" => "",  "state" => ""),
            array("code" => "TL", "capital" => "Dili", "postcode" => "",  "state" => ""),
            array("code" => "TG", "capital" => "Lome", "postcode" => "",  "state" => ""),
            array("code" => "TO", "capital" => "Nuku'alofa", "postcode" => "",  "state" => ""),
            array("code" => "TT", "capital" => "Port of Spain", "postcode" => "",  "state" => "", "suburb" => "PORT OF SPAIN"),
            array("code" => "TN", "capital" => "Tunis airport", "postcode" => "2079",  "state" => ""),
            array("code" => "TR", "capital" => "ALTINDAG ANKARA OTHERS", "postcode" => "06140",  "state" => ""),
            array("code" => "TM", "capital" => "Ashgabat", "postcode" => "744000",  "state" => ""),
            array("code" => "TC", "capital" => "Cockburn Town", "postcode" => "",  "state" => ""),
            array("code" => "TV", "capital" => "Funafuti", "postcode" => "",  "state" => ""),
            array("code" => "UG", "capital" => "Kampala", "postcode" => "",  "state" => ""),
            array("code" => "UA", "capital" => "Kiev", "postcode" => "",  "state" => ""),
            array("code" => "AE", "capital" => "Abu Dhabi", "postcode" => "",  "state" => ""),
            array("code" => "GB", "capital" => "London", "postcode" => "E109",  "state" => ""),
            array("code" => "US", "capital" => "Washington", "postcode" => "52353",  "state" => "IA"),
            array("code" => "UY", "capital" => "Montevideo", "postcode" => "",  "state" => ""),
            array("code" => "UZ", "capital" => "Tashkent", "postcode" => "100187",  "state" => ""),
            array("code" => "VU", "capital" => "Port Vila", "postcode" => "",  "state" => ""),
            array("code" => "VE", "capital" => "Caracas", "postcode" => "",  "state" => ""),
            array("code" => "VN", "capital" => "Hanoi", "postcode" => "",  "state" => ""),
            array("code" => "VG", "capital" => "Road Town", "postcode" => "",  "state" => ""),
            array("code" => "VI", "capital" => "Charlotte Amalie", "postcode" => "00801",  "state" => "AB"),
            array("code" => "WF", "capital" => "Mata Utu", "postcode" => "",  "state" => ""),
            array("code" => "EH", "capital" => "El-Aaiun", "postcode" => "",  "state" => ""),
            array("code" => "YE", "capital" => "Sanaa", "postcode" => "",  "state" => ""),
            array("code" => "ZM", "capital" => "Lusaka", "postcode" => "",  "state" => ""),
            array("code" => "ZW", "capital" => "Harare", "postcode" => "",  "state" => "")
        );
    }

    private function set_no_postalcode_countries()
    {

        $this->no_postalcode_countries = [
            'AE',
            'AF',
            'AG',
            'AI',
            'AL',
            'AN',
            'AO',
            'AW',
            'BB',
            'BF',
            'BH',
            'BI',
            'BJ',
            'BM',
            'BO',
            'BS',
            'BT',
            'BW',
            'BZ',
            'CD',
            'CF',
            'CG',
            'CI',
            'CK',
            'CL',
            'CM',
            'CO',
            'CR',
            'CV',
            'DJ',
            'DM',
            'DO',
            'EC',
            'EG',
            'ER',
            'ET',
            'FJ',
            'FK',
            'GA',
            'GD',
            'GH',
            'GI',
            'GM',
            'GN',
            'GQ',
            'GT',
            'GW',
            'GY',
            'HK',
            'HN',
            'HT',
            'IE',
            'IQ',
            'IR',
            'JM',
            'JO',
            'KE',
            'KH',
            'KI',
            'KM',
            'KN',
            'KP',
            'KW',
            'KY',
            'LA',
            'LB',
            'LC',
            'LK',
            'LR',
            'LS',
            'LY',
            'ML',
            'MM',
            'MO',
            'MR',
            'MS',
            'MT',
            'MU',
            'MW',
            'MZ',
            'NA',
            'NE',
            'NG',
            'NI',
            'NP',
            'NR',
            'NU',
            'OM',
            'PA',
            'PE',
            'PF',
            'PY',
            'QA',
            'RW',
            'SA',
            'SB',
            'SC',
            'SD',
            'SL',
            'SN',
            'SO',
            'SR',
            'SS',
            'ST',
            'SV',
            'SY',
            'TC',
            'TD',
            'TG',
            'TL',
            'TO',
            'TT',
            'TV',
            'TZ',
            'UG',
            'UY',
            'VC',
            'VE',
            'VG',
            'VN',
            'VU',
            'WS',
            'XA',
            'XB',
            'XC',
            'XE',
            'XL',
            'XM',
            'XN',
            'XS',
            'YE',
            'ZM',
            'ZW'
        ];
    }

    public function get_country_name_by_code($code)
    {
        return $this->countries[$code];
    }

    public function get_all()
    {
        return $this->countries;
    }

    public function get_postcode_city_by_country($code)
    {
        $key = array_search($code, array_column($this->capitals, 'code'));
        return $this->capitals[$key];
    }

    public function get_no_postalcode_countries()
    {
        return $this->no_postalcode_countries;
    }
}
